# Generated by Django 2.1.15 on 2020-08-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200823_1514'),
        ('authentication', '0027_auto_20200819_2120'),
    ]

    operations = [
    ]
